"""auto-users-phone

Revision ID: bae79c75fa48
Revises: d00badc39ec4
Create Date: 2024-08-05 15:57:22.283510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae79c75fa48'
down_revision: Union[str, None] = 'd00badc39ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('users', 'phone')
    op.add_column('users', sa.Column('phone', sa.String(), nullable=False))
    # ### end Alembic commands ###  
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
    pass